#!/usr/bin/env python3
"""Generate the Lean certificate data from the canonical mod-31 equation."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


PRIME = 31
SPECIALIZATION = 7
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/modular/f4_mod_31.json"
OUTPUT = ROOT / "verification/lean/M23Certificate/Data.lean"


def trim(a: list[int]) -> list[int]:
    a = [x % PRIME for x in a]
    while a and a[-1] == 0:
        a.pop()
    return a


def add(a: list[int], b: list[int]) -> list[int]:
    n = max(len(a), len(b))
    return trim([(a[i] if i < len(a) else 0) + (b[i] if i < len(b) else 0) for i in range(n)])


def sub(a: list[int], b: list[int]) -> list[int]:
    n = max(len(a), len(b))
    return trim([(a[i] if i < len(a) else 0) - (b[i] if i < len(b) else 0) for i in range(n)])


def scale(a: list[int], c: int) -> list[int]:
    return trim([c * x for x in a])


def mul(a: list[int], b: list[int]) -> list[int]:
    if not a or not b:
        return []
    out = [0] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        for j, y in enumerate(b):
            out[i + j] = (out[i + j] + x * y) % PRIME
    return trim(out)


def divmod_poly(a: list[int], b: list[int]) -> tuple[list[int], list[int]]:
    a = trim(a)
    b = trim(b)
    if not b:
        raise ZeroDivisionError("zero polynomial")
    q = [0] * max(0, len(a) - len(b) + 1)
    inv = pow(b[-1], -1, PRIME)
    while len(a) >= len(b):
        degree = len(a) - len(b)
        coefficient = a[-1] * inv % PRIME
        q[degree] = coefficient
        for j, value in enumerate(b):
            a[degree + j] = (a[degree + j] - coefficient * value) % PRIME
        a = trim(a)
    return trim(q), a


def pow_poly(a: list[int], exponent: int) -> list[int]:
    out = [1]
    base = a
    while exponent:
        if exponent & 1:
            out = mul(out, base)
        base = mul(base, base)
        exponent >>= 1
    return out


def extended_gcd(a: list[int], b: list[int]) -> tuple[list[int], list[int], list[int]]:
    old_r, r = trim(a), trim(b)
    old_s, s = [1], []
    old_t, t = [], [1]
    while r:
        q, remainder = divmod_poly(old_r, r)
        old_r, r = r, remainder
        old_s, s = s, sub(old_s, mul(q, s))
        old_t, t = t, sub(old_t, mul(q, t))
    inverse_lc = pow(old_r[-1], -1, PRIME)
    return scale(old_r, inverse_lc), scale(old_s, inverse_lc), scale(old_t, inverse_lc)


def lean_list(values: list[int]) -> str:
    return "[" + ", ".join(map(str, values)) + "]"


def lean_matrix(rows: list[list[int]], indent: str = "  ") -> str:
    return "[\n" + ",\n".join(indent + lean_list(row) for row in rows) + "\n]"


def build() -> str:
    raw = SOURCE.read_bytes()
    data = json.loads(raw)
    rows = data["coefficients_T_then_W"]
    assert data["prime"] == PRIME
    assert data["degree_T"] == 4 and data["degree_W"] == 23
    assert data["status"] == "PASS_OPTIMAL_23_4_MOD_PRIME"
    assert len(rows) == 5 and all(len(row) == 24 for row in rows)
    assert data["normalization_coefficient"] == "T^4*W^23 = 1"

    # Outer variable W, inner variable T.
    w_coefficients = [[rows[i][j] for i in range(5)] for j in range(24)]
    primitive_gcd, primitive_a, primitive_b = extended_gcd(w_coefficients[0], w_coefficients[1])
    assert primitive_gcd == [1]
    assert add(mul(primitive_a, w_coefficients[0]), mul(primitive_b, w_coefficients[1])) == [1]
    primitive_identity_length = max(
        len(primitive_a) + len(w_coefficients[0]) - 1,
        len(primitive_b) + len(w_coefficients[1]) - 1,
    )
    primitive_identity = [1] + [0] * (primitive_identity_length - 1)
    p7 = [sum(rows[i][j] * SPECIALIZATION**i for i in range(5)) % PRIME for j in range(24)]
    assert p7[-1] == 14
    monic_scale = pow(p7[-1], -1, PRIME)
    assert monic_scale == 20
    f = scale(p7, monic_scale)
    assert len(f) == 24 and f[-1] == 1

    remainders = [[0, 1]]
    quotients: list[list[int]] = []
    for _ in range(23):
        powered = pow_poly(remainders[-1], PRIME)
        quotient, remainder = divmod_poly(powered, f)
        quotients.append(quotient)
        remainders.append(remainder)
        assert add(mul(quotient, f), remainder) == powered
    assert remainders[-1] == [0, 1]

    frobenius_one = [0] * 32
    frobenius_one[1] = -1 % PRIME
    frobenius_one[31] = 1
    gcd, bezout_a, bezout_b = extended_gcd(f, frobenius_one)
    assert gcd == [1]
    assert add(mul(bezout_a, f), mul(bezout_b, frobenius_one)) == [1]
    bezout_identity_length = max(
        len(bezout_a) + len(f) - 1,
        len(bezout_b) + len(frobenius_one) - 1,
    )
    bezout_identity = [1] + [0] * (bezout_identity_length - 1)

    source_hash = hashlib.sha256(raw).hexdigest()
    return f'''/- This file is generated by scripts/emit_lean_certificate_data.py.
Source: data/modular/f4_mod_31.json
SHA-256: {source_hash}
-/
import M23Certificate.Coefficients

open Polynomial

namespace M23Certificate.Data

set_option maxRecDepth 100000

abbrev F31 := ZMod 31

def toF31 (coefficients : List ℕ) : List F31 :=
  coefficients.map fun n => (n : F31)

/-- A coefficient-list constructor in ascending degree order. -/
noncomputable abbrev fromCoefficients {{R : Type*}} [CommSemiring R] :=
  M23Certificate.Coefficients.realize (R := R)

/-- Coefficients of P(T,W), indexed first by W-degree and then by T-degree. -/
def coefficientsWThenT : List (List ℕ) :=
{lean_matrix(w_coefficients)}

/-- The canonical bivariate polynomial P(T,W) over F_31, with W outermost. -/
noncomputable def P : (F31[X])[X] :=
  fromCoefficients (coefficientsWThenT.map fun row =>
    fromCoefficients (toF31 row))

def primitiveACoefficients : List ℕ := {lean_list(primitive_a)}
def primitiveBCoefficients : List ℕ := {lean_list(primitive_b)}
def primitiveIdentityCoefficients : List ℕ := {lean_list(primitive_identity)}

noncomputable def primitiveA : F31[X] := fromCoefficients (toF31 primitiveACoefficients)
noncomputable def primitiveB : F31[X] := fromCoefficients (toF31 primitiveBCoefficients)

def p7Coefficients : List ℕ := {lean_list(p7)}

/-- The specialization P(7,W), recorded independently for a checked data bridge. -/
noncomputable def p7 : F31[X] := fromCoefficients (toF31 p7Coefficients)

def p7MonicCoefficients : List ℕ := {lean_list(f)}

/-- The monic associate 20 * P(7,W); 20 is the inverse of its leading coefficient 14. -/
noncomputable def p7Monic : F31[X] := fromCoefficients (toF31 p7MonicCoefficients)

/-- Successive remainders in the 31-power Frobenius chain. -/
def frobeniusRemainderCoefficients : List (List ℕ) :=
{lean_matrix(remainders)}

/-- Quotient witnesses for every step of the Frobenius chain. -/
def frobeniusQuotientCoefficients : List (List ℕ) :=
{lean_matrix(quotients)}

def frobeniusOneCoefficients : List ℕ := {lean_list(frobenius_one)}

def frobeniusRemainderRaw (i : ℕ) : List F31 :=
  toF31 (frobeniusRemainderCoefficients.getD i [])

def frobeniusQuotientRaw (i : ℕ) : List F31 :=
  toF31 (frobeniusQuotientCoefficients.getD i [])

noncomputable def frobeniusRemainder (i : ℕ) : F31[X] :=
  fromCoefficients (frobeniusRemainderRaw i)

noncomputable def frobeniusQuotient (i : ℕ) : F31[X] :=
  fromCoefficients (frobeniusQuotientRaw i)

def bezoutACoefficients : List ℕ := {lean_list(bezout_a)}
def bezoutBCoefficients : List ℕ := {lean_list(bezout_b)}
def bezoutIdentityCoefficients : List ℕ := {lean_list(bezout_identity)}

noncomputable def bezoutA : F31[X] := fromCoefficients (toF31 bezoutACoefficients)
noncomputable def bezoutB : F31[X] := fromCoefficients (toF31 bezoutBCoefficients)

end M23Certificate.Data
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated data is stale")
    args = parser.parse_args()
    rendered = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
        print(f"PASS: {OUTPUT.relative_to(ROOT)} is current")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered)
        print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
