#!/usr/bin/env python3
"""Emit a self-contained Magma certificate for the optimal (23,4) model."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUTPUT = ROOT / "verification" / "verify_optimal_23_4.m"


def integer_table(path: Path, key: str | None = None) -> list[list[int]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    raw = payload if key is None else payload[key]
    return [[int(value) for value in row] for row in raw]


def pencil_table(encoded: dict[str, str], v_degree: int, t_degree: int) -> list[list[int]]:
    table = [[0 for _ in range(t_degree + 1)] for _ in range(v_degree + 1)]
    for key, value in encoded.items():
        v_index, t_index = map(int, key.split(","))
        table[v_index][t_index] = int(value)
    return table


def magma_matrix(name: str, rows: list[list[int]]) -> str:
    body = ",\n".join("    [" + ",".join(map(str, row)) + "]" for row in rows)
    return f"{name} := [\n{body}\n];\n"


def validate(
    source: list[list[int]],
    equation: list[list[int]],
    pencil: list[list[list[int]]],
) -> None:
    if len(source) != 24 or any(len(row) != 9 for row in source):
        raise SystemExit("unexpected source coefficient-table dimensions")
    if len(equation) != 5 or any(len(row) != 24 for row in equation):
        raise SystemExit("unexpected optimal-model coefficient-table dimensions")
    if len(pencil) != 2 or len(pencil[0]) != 21 or len(pencil[1]) != 22:
        raise SystemExit("unexpected pencil coefficient-table dimensions")
    content = 0
    for row in equation:
        for coefficient in row:
            content = math.gcd(content, abs(coefficient))
    if content != 1:
        raise SystemExit("optimal equation is not primitive")
    if equation[4][23] == 0 or equation[4][23] % 31 == 0:
        raise SystemExit("corner coefficient does not retain bidegree modulo 31")


def render() -> str:
    source = integer_table(DATA / "Fint_coefficients_Z.json")
    equation = integer_table(
        DATA / "optimal_23_4_Z.json", "coefficients_T_then_W"
    )
    pencil_payload = json.loads(
        (DATA / "optimal_degree4_pencil.json").read_text(encoding="utf-8")
    )
    if pencil_payload.get("status") != "PASS_EXACT_PENCIL_EMISSION":
        raise SystemExit("pencil JSON does not carry the expected PASS status")
    encoded = pencil_payload["expanded_coefficients_V_then_T"]
    pencil = [pencil_table(encoded[0], 20, 6), pencil_table(encoded[1], 21, 6)]
    validate(source, equation, pencil)

    header = r'''// Self-contained exact Magma certificate for the optimal (23,4) model.
// Generated deterministically by scripts/emit_magma_certificate.py from the
// canonical JSON coefficient tables.  Do not edit this file by hand.
//
// The certificate checks:
//   (1) P(T,W) is primitive of bidegree (23,4), retaining that bidegree mod 31;
//   (2) J1^23 P(T,J0/J1) is zero in Q(T)[V]/(F);
//   (3) P mod 31 is irreducible in F_31[T,W].

DO_EXACT_IDENTITY := true;
DO_FINITE_IRREDUCIBILITY := true;

'''
    tables = "\n".join(
        [
            magma_matrix("FINT_V_THEN_T", source),
            magma_matrix("P_T_THEN_W", equation),
            magma_matrix("J0_V_THEN_T", pencil[0]),
            magma_matrix("J1_V_THEN_T", pencil[1]),
        ]
    )
    program = r'''
content := 0;
for row in P_T_THEN_W do
    for coefficient in row do
        content := GCD(content, Abs(coefficient));
    end for;
end for;
assert content eq 1;
assert P_T_THEN_W[5][24] ne 0;
assert (P_T_THEN_W[5][24] mod 31) ne 0;

if DO_EXACT_IDENTITY then
    Q := Rationals();
    KT<T> := FunctionField(Q);
    RV<V> := PolynomialRing(KT);

    function PolynomialInT(coefficients)
        value := KT!0;
        for i in [1..#coefficients] do
            value +:= (KT!coefficients[i]) * T^(i - 1);
        end for;
        return value;
    end function;

    Fint := RV![ PolynomialInT(row) : row in FINT_V_THEN_T ];
    D := T^2 + 23;
    F := RV![ Coefficient(Fint, i) / D^4 : i in [0..Degree(Fint)] ];
    assert Degree(F) eq 23;
    assert IsMonic(F);

    J0 := RV![ PolynomialInT(row) : row in J0_V_THEN_T ];
    J1 := RV![ PolynomialInT(row) : row in J1_V_THEN_T ];
    assert Degree(J0) eq 20;
    assert Degree(J1) eq 21;

    p_coefficients := [];
    for j in [1..24] do
        coefficient := KT!0;
        for i in [1..5] do
            coefficient +:= (KT!P_T_THEN_W[i][j]) * T^(i - 1);
        end for;
        Append(~p_coefficients, coefficient);
    end for;

    numerator := RV!p_coefficients[24];
    J1power := J1;
    for j := 22 to 0 by -1 do
        numerator := (numerator * J0 + p_coefficients[j + 1] * J1power) mod F;
        if j gt 0 then
            J1power := (J1power * J1) mod F;
        end if;
    end for;
    assert numerator eq 0;
    print "PASS_MAGMA_EXACT_FUNCTION_FIELD_IDENTITY";
end if;

if DO_FINITE_IRREDUCIBILITY then
    k := GF(31);
    S<t,w> := PolynomialRing(k, 2);
    P31 := S!0;
    for i in [0..4] do
        for j in [0..23] do
            P31 +:= (k!P_T_THEN_W[i + 1][j + 1]) * t^i * w^j;
        end for;
    end for;
    assert Degree(P31, 1) eq 4;
    assert Degree(P31, 2) eq 23;
    assert MonomialCoefficient(P31, t^4*w^23) ne 0;
    assert IsIrreducible(P31);
    print "PASS_MAGMA_IRREDUCIBLE_MOD_31";
end if;

print "PASS_OPTIMAL_23_4_MAGMA_CERTIFICATE";
'''
    return header + tables + program


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render()
    if args.write:
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"WROTE {OUTPUT.relative_to(ROOT)} ({len(expected.encode('utf-8'))} bytes)")
        return
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
        raise SystemExit(
            "stale generated Magma certificate; run "
            "scripts/emit_magma_certificate.py --write"
        )
    print("PASS deterministic Magma certificate rendering")


if __name__ == "__main__":
    main()
